on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

permissions:
  contents: read

name: CI
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
#          - 'macos-latest' // we rely on testcontainers
#          - 'windows-latest'
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
      - name: Install msodbcsql18
        run: |
          sudo apt-get update
          sudo apt-get install -y msodbcsql18
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'
      - uses: chartboost/ruff-action@v1
      - name: Test with pytest
        run: |
          # -n0 disables parallel tests for more stability
          pytest -n0
