on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Go
        uses: actions/setup-go@v4
        with:
          go-version: '~1.20'
      - name: Integration Test
        run: go build ./cmd/datacontract.go && ./datacontract init && ./datacontract lint
